name: Run PowerShell Script

on:
  workflow_dispatch:

jobs:
  run-powershell:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run script file
        run: ./hello.ps1
        shell: pwsh

