name: Update Dynamic README

on:
  schedule:
    - cron: "0 * * * *" # Runs every hour (UTC)
  workflow_dispatch: # Allow manual run from GitHub Actions tab

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo with write permissions
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # fetch full history
          token: ${{ secrets.GITHUB_TOKEN }} # so git push works

      # 2️⃣ Generate dynamic README content
      - name: Update README.md
        run: |
          echo "## Dynamic README" > README.md
          echo "" >> README.md
          echo "Updated on: $(date)" >> README.md
          echo "" >> README.md
          echo "Random number: $RANDOM" >> README.md

      # 3️⃣ Configure Git identity (GitHub Actions bot)
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # 4️⃣ Commit changes only if README.md actually changed
      - name: Commit Changes
        run: |
          git add README.md
          git diff --cached --quiet || git commit -m "📄 Update README (auto-generated)"

      # 5️⃣ Push changes to main
      - name: Push Changes
        run: git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
